project: 
  type: book

book: 
  title: "Akkutte effekter av apné og bikarbonat på sykkelprestasjon"
  author: "Anders Nybakk"
  date: "15.05.2026"
  chapters: 
    - acknowledgements.qmd
    - abstract.qmd
    - index.qmd
    - theory.qmd
    - introduction.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - references.qmd

bibliography: resources/bib-final.bib

format:
  html:
    mainfont: "Times New Roman"
  pdf:
    mainfont: "Times New Roman"
  docx:
    reference-doc: reference-doc.docx 
    
  